# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cookbook - a collection of recipes
email: jamie@verticalgraindesign.com
description: > # this means to ignore newlines until "baseurl:"
  Recipes that are mostly vegetable based, use simple ingredients, and are cheap to prepare. 
# baseurl: "/cookbook" # the subpath of your site, e.g. /blog
url: "http://verticalgraindesign.com/cookbook" # the base hostname & protocol for your site
github_username:  verticalgrain

# Build settings
markdown: kramdown
permalink: /:title
sass:
  sass_dir: _scss